version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-sid-node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/firebase/emulators
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          command: npm run firestore-emulator
          background: true
      - run: npm run test:unit
